services:
  postgres:
    image: postgres:15
    container_name: sso_postgres
    restart: always
    environment:
      POSTGRES_USER: sso_user
      POSTGRES_PASSWORD: sso_pass
      POSTGRES_DB: sso_db
    ports:
      - "5432:5432"